### ISSUE TITLE
Does not work with love 0.10.1

### ISSUE THREAD

**Issue by AlexYeCu** [Starkkz/light-vs-shadow#3]
love 0.10.1

Error: lib/light.lua:4: attempt to index field 'light' (a nil value)
stack traceback:
        lib/light.lua:4: in main chunk
        [C]: in function 'require'
        functions/playingState.lua:24: in function 'load'
        functions/playingState.lua:15: in function 'start'
        main.lua:31: in function 'allLoaded'
        lib/love-loader.lua:143: in function 'endThreadIfAllLoaded'
        lib/love-loader.lua:182: in function 'update'
        functions/loadingState.lua:427: in function 'update'
        main.lua:100: in function 'update'
        [string "boot.lua"]:463: in function <[string "boot.lua"]:435>
        [C]: in function 'xpcall'

------------------
(program exited with code: 1)
Press return to continue

**Comment by Starkkz** [comment]
Out of curiosity how do you require the light engine?

**Comment by AlexYeCu** [comment]
require "lib.postshader"
require "lib.light"
All third party things placed to /lib directory (/ — project's root).

**Comment by Starkkz** [comment]
Could you place the folder "livsh" inside "lib", and use:
require "lib.livsh"

You may get another error, if you want to continue forward with this I must advise you that I removed most of the shadow types except the polygon shadow.

**Comment by AlexYeCu** [comment]
Error: lib/livsh/world.lua:557: attempt to index local 'self' (a number value)
stack traceback:
        lib/livsh/world.lua:557: in function 'setBlur'
        functions/playingState.lua:88: in function 'load'
        functions/playingState.lua:15: in function 'start'
        main.lua:31: in function 'allLoaded'
        lib/love-loader.lua:143: in function 'endThreadIfAllLoaded'
        lib/love-loader.lua:182: in function 'update'
        functions/loadingState.lua:427: in function 'update'
        main.lua:100: in function 'update'
        [string "boot.lua"]:463: in function <[string "boot.lua"]:435>
        [C]: in function 'xpcall'

String 88 of playingState.lua:
	lightWorld = love.light.newWorld();
	lightWorld.setBlur(32); <-- string 88

> removed most of the shadow types except the polygon shadow

Well, my project has isometric (almost)  view, so shadows turned off by default.

**Comment by Starkkz** [comment]
Can you try changing all the "." into ":" on object calls? It may work if you do it like this:
lightWorld:setBlur(32)

**Comment by AlexYeCu** [comment]
Oh, I should read error messages carefully.
Thank you for porting the lib and support: everything looks working now.
